### ISSUE TITLE
Add file rename capabilities to file explorer

### ISSUE THREAD

**Issue by aaronbartell** [shortty/splitty#7]
Really like the simplicity of this app.  Not sure if you are welcoming feature suggestions, but thought I'd submit some (and hopefully do PRs to accomplish them).

Currently the File Explorer doesn't allow for renaming of files and instead a developer would have to use the `mv` command from the shell.  Would be great if user could click on a file and have it turn into an input field for renaming (similar to how renaming works on OSX).

**Comment by PMoneda** [comment]
Hi, @aaronbartell patches are welcome you can send your PR's
Have fun!

**Comment by PMoneda** [comment]
It's done!, File Explorer now support Create File or Folder, delete and rename
